/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duan1.ui;

import com.duan1.dao.NhanVienDAO;
import com.duan1.entity.NhanVien;
import com.duan1.utils.Auth;

/**
 *
 * @author admin
 */
public class DangNhap1JDialog extends javax.swing.JDialog {

    /**
     * Creates new form DangNhap1JDialog
     */
    public DangNhap1JDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAnhNen = new javax.swing.JPanel();
        pnlNoiDung = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        txtMaNV = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnKetThuc = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        chkShowPass = new javax.swing.JCheckBox();
        txt_trangthai = new javax.swing.JLabel();
        btn_qrcode = new javax.swing.JButton();
        btn_doimk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setModal(true);
        setUndecorated(true);
        getContentPane().setLayout(null);

        pnlAnhNen.setLayout(null);

        pnlNoiDung.setBackground(new java.awt.Color(51, 51, 51));
        pnlNoiDung.setForeground(new java.awt.Color(51, 51, 51));
        pnlNoiDung.setLayout(null);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSeparator3.setMinimumSize(new java.awt.Dimension(310, 15));
        jSeparator3.setPreferredSize(new java.awt.Dimension(0, 5));
        pnlNoiDung.add(jSeparator3);
        jSeparator3.setBounds(20, 150, 310, 10);

        txtMaNV.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtMaNV.setForeground(new java.awt.Color(255, 255, 255));
        txtMaNV.setText("dungt02");
        txtMaNV.setAlignmentY(0.0F);
        txtMaNV.setAutoscrolls(false);
        txtMaNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMaNV.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMaNV.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        txtMaNV.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMaNV.setFocusCycleRoot(true);
        txtMaNV.setHighlighter(null);
        txtMaNV.setOpaque(false);
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });
        pnlNoiDung.add(txtMaNV);
        txtMaNV.setBounds(60, 170, 260, 30);

        txtMatKhau.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        txtMatKhau.setText("123");
        txtMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txtMatKhau.setOpaque(false);
        pnlNoiDung.add(txtMatKhau);
        txtMatKhau.setBounds(60, 220, 260, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\DUAN1\\DUAN1\\src\\com\\duan1\\icon\\User.png")); // NOI18N
        pnlNoiDung.add(jLabel3);
        jLabel3.setBounds(0, 160, 50, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\DUAN1\\DUAN1\\src\\com\\duan1\\icon\\Key.png")); // NOI18N
        pnlNoiDung.add(jLabel4);
        jLabel4.setBounds(0, 220, 50, 50);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(0, 5));
        pnlNoiDung.add(jSeparator2);
        jSeparator2.setBounds(20, 280, 310, 10);

        btnKetThuc.setBackground(new java.awt.Color(204, 0, 0));
        btnKetThuc.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnKetThuc.setForeground(new java.awt.Color(255, 255, 255));
        btnKetThuc.setText("KẾT THÚC");
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });
        pnlNoiDung.add(btnKetThuc);
        btnKetThuc.setBounds(230, 440, 100, 30);

        btnDangNhap.setBackground(new java.awt.Color(0, 0, 102));
        btnDangNhap.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        pnlNoiDung.add(btnDangNhap);
        btnDangNhap.setBounds(20, 300, 310, 40);

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");
        pnlNoiDung.add(jLabel2);
        jLabel2.setBounds(130, 60, 80, 60);

        chkShowPass.setForeground(new java.awt.Color(255, 255, 255));
        chkShowPass.setText("Hiện mật khẩu!!");
        chkShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkShowPassActionPerformed(evt);
            }
        });
        pnlNoiDung.add(chkShowPass);
        chkShowPass.setBounds(20, 350, 110, 20);

        txt_trangthai.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_trangthai.setForeground(new java.awt.Color(255, 0, 0));
        txt_trangthai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_trangthai.setText("Trạng Thái");
        txt_trangthai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlNoiDung.add(txt_trangthai);
        txt_trangthai.setBounds(0, 420, 350, 17);

        btn_qrcode.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\DUAN1\\DUAN1\\src\\com\\duan1\\icon\\qr-code.png")); // NOI18N
        btn_qrcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qrcodeActionPerformed(evt);
            }
        });
        pnlNoiDung.add(btn_qrcode);
        btn_qrcode.setBounds(160, 380, 50, 40);

        btn_doimk.setText("Đổi mật khẩu");
        btn_doimk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doimkActionPerformed(evt);
            }
        });
        pnlNoiDung.add(btn_doimk);
        btn_doimk.setBounds(140, 350, 100, 20);

        pnlAnhNen.add(pnlNoiDung);
        pnlNoiDung.setBounds(490, 10, 350, 480);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\DUAN1\\DUAN1\\src\\com\\duan1\\icon\\content.jpg")); // NOI18N
        pnlAnhNen.add(jLabel5);
        jLabel5.setBounds(10, 10, 480, 480);

        getContentPane().add(pnlAnhNen);
        pnlAnhNen.setBounds(210, 130, 850, 500);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("QUẢN LÝ BÁN ĐÀN");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 40, 490, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Desktop\\DUAN1\\DUAN1\\src\\com\\duan1\\icon\\background5.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        // TODO add your handling code here:
        this.ketThuc();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        this.dangNhap();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void chkShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPassActionPerformed
        // TODO add your handling code here:
        if(chkShowPass.isSelected()){
            txtMatKhau.setEchoChar((char)0);
        }else{
            txtMatKhau.setEchoChar('*');
        }
    }//GEN-LAST:event_chkShowPassActionPerformed

    private void btn_doimkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doimkActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DoiMatKhauJDialog1(null, true).setVisible(true);
    }//GEN-LAST:event_btn_doimkActionPerformed

    private void btn_qrcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qrcodeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new QRCODE1(null,true).setVisible(true);
    }//GEN-LAST:event_btn_qrcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap1JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap1JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap1JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap1JDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhap1JDialog dialog = new DangNhap1JDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btn_doimk;
    private javax.swing.JButton btn_qrcode;
    private javax.swing.JCheckBox chkShowPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pnlAnhNen;
    public javax.swing.JPanel pnlNoiDung;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JLabel txt_trangthai;
    // End of variables declaration//GEN-END:variables
 NhanVienDAO dao = new NhanVienDAO();
    private void init() {
         setLocationRelativeTo(null);
        
        txtMaNV.setBackground(new java.awt.Color(0, 0, 0, 1));
        txtMatKhau.setBackground(new java.awt.Color(0, 0, 0, 1));
        pnlAnhNen.setBackground(new java.awt.Color(0, 0, 0, 1));
        chkShowPass.setBackground(new java.awt.Color(0, 0, 0, 1));
        new Chao1JDialog(null, true).setVisible(true);
    }


    void dangNhap() {
        String Manhanvien = txtMaNV.getText();
        String matKhau = new String(txtMatKhau.getPassword());
        NhanVien nhanVien = dao.selectById(Manhanvien);
        if(nhanVien == null){
           txt_trangthai.setText("Vui lòng nhập đầy đủ thông tin!");
        }
        else if(!matKhau.equals(nhanVien.getMatkhau())){
            txt_trangthai.setText("Nhập sai thông tin!");
        }
        else{
           
            Auth.user = nhanVien;
            this.dispose();
            new TrangChuAdminJDialog().setVisible(true);
            
            
        }
    }

    void ketThuc() {
        //if (MsgBox.confirm(this, "Bạn muốn kết thúc ứng dụng?")) {
        System.exit(0);
        //}
    }
}
